### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by ShroyerL** [warthog-cpr/warthog#23]
Hi, when I try to build the warthog urdf, it says that "resource not found: warthog_description". I saw that you commented on someone else's concern about that, but I have warthog_description cloned to where it needs to be.

**Comment by tonybaltovski** [comment]
Hi @ShroyerL can you provide the steps you took please?

**Comment by ShroyerL** [comment]
I made a workspace.
git clone https://github.com/warthog-cpr/warthog.git
built the workspace with catkin_make
devel/setup.bat
navigated to the urdf folder under the warthog_description folder.
rosrun xacro xacro warthog.urdf.xacro > warthog.urdf
returns an error that says "resource not found: warthog_description"

**Comment by tonybaltovski** [comment]
Is this on Windows? Can you `roscd warthog_description' after building sourcing? I think the best bet would be to ask the ROS community, (https://robotics.stackexchange.com) there's usually plenty of ROS experts there that will be willing to help who might have experience with ROS on Windows.

**Comment by ShroyerL** [comment]
Yes, I am using Windows. I just tried "roscd warthog_description", and it did say that it wasn't found. Is there something I need to add to the CMakeList.txt?

**Comment by tonybaltovski** [comment]
Take a look at Jackal J100: https://github.com/jackal/jackal/blob/noetic-devel/jackal_description/CMakeLists.txt

**Comment by ShroyerL** [comment]
Adding that portion about win32 didn't help. I am wondering if I need to remove ROS1 on my machine and start over with ROS2. I didn't have this problem a short while ago. I already made the urdf once. For some reason I can't repeat it. Can you recommend a page on which the recommended c project tools are outlined?

**Comment by tonybaltovski** [comment]
I am going to close this since it not related to the software of this repository.  Try asking the ROS community, (https://robotics.stackexchange.com/) which might have insight into using ROS on Windows.
