### ISSUE TITLE
Cannot launch warthog simulation

### ISSUE THREAD

**Issue by dfvneto** [warthog-cpr/warthog#5]
Hi
I got this errors when I tried to launch warthog_world.launch

[ERROR] [1523654557.519325482, 0.204000000]: Could not load controller 'warthog_joint_publisher' because controller type 'joint_state_controller/JointStateController' does not exist.
[ERROR] [1523654557.519374846, 0.204000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [1523654558.520654, 1.204000]: Failed to load warthog_joint_publisher

[ERROR] [1523654558.523138521, 1.207000000]: Could not load controller 'warthog_velocity_controller' because controller type 'diff_drive_controller/DiffDriveController' does not exist.
[ERROR] [1523654558.523181791, 1.207000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [1523654559.523923, 2.206000]: Failed to load warthog_velocity_controller

I used rosservice and got this output:
types: []
base_classes: []

**Comment by tonybaltovski** [comment]
Did you install this from source or debs?  If from source, make sure you install the dependencies. You could use `rosdep` inside of the workspace such as `rosdep install --from-paths src --ignore-src --rosdistro=$ROS_DISTRO -y`.

**Comment by dfvneto** [comment]
Yes thank you. I forgot to install the dependencies. I installed everything and it worked smoothly.
