### ISSUE TITLE
UR arms breaks - Warthog description update

### ISSUE THREAD

**Issue by tahir1069** [warthog-cpr/warthog#8]
I am trying to update warthog description, by attaching three universal robot arms(2 UR5, 1 UR3). I am following the second  approach pointed [here](http://www.clearpathrobotics.com/assets/guides/kinetic/warthog/WarthogStartup.html#adding-urdf). I was succesfull in adding all the robot descriptions needed. But UR arm breaks which actually is included later. In the following example:
```
  <xacro:include filename="$(find mbs_description)/urdf/accessories/arms/right_ur_arm.urdf.xacro" />
  <xacro:if value="$(optenv WARTHOG_RIGHT_ARM 0)">
    <joint name="right_arm_joint" type="fixed">
      <origin xyz="0 0 -0.025" rpy="0 0 0" />
      <parent link="right_arm_mount_link"/>
      <child link="right_arm/base_link" />
    </joint>
  </xacro:if>

  <xacro:include filename="$(find mbs_description)/urdf/accessories/arms/left_ur_arm.urdf.xacro" />
  <xacro:if value="$(optenv WARTHOG_LEFT_ARM 0)">
    <joint name="left_arm_joint" type="fixed">
      <origin xyz="0 0 -0.025" rpy="0 0 0" />
      <parent link="left_arm_mount_link"/>
      <child link="left_arm/base_link" />
    </joint>
  </xacro:if>
  
  <xacro:include filename="$(find mbs_description)/urdf/accessories/arms/center_ur_arm.urdf.xacro" />
  <xacro:if value="$(optenv WARTHOG_CENTER_ARM 0)">
    <joint name="center_arm_joint" type="fixed">
      <origin xyz="0 0 -0.025" rpy="0 0 3.1415" />
      <parent link="center_arm_mount_link"/>
      <child link="center_arm/base_link" />
    </joint>
  </xacro:if>
```

Here I have added right and left (both UR5e) and than center(UR3), so the arm in the center breaks its joints and goes to the length of UR5e. 

And if I take the center arm at the top like here:

```
<xacro:include filename="$(find mbs_description)/urdf/accessories/arms/center_ur_arm.urdf.xacro" />
  <xacro:if value="$(optenv WARTHOG_CENTER_ARM 0)">
    <joint name="center_arm_joint" type="fixed">
      <origin xyz="0 0 -0.025" rpy="0 0 3.1415" />
      <parent link="center_arm_mount_link"/>
      <child link="center_arm/base_link" />
    </joint>
  </xacro:if>
  
  <xacro:include filename="$(find mbs_description)/urdf/accessories/arms/right_ur_arm.urdf.xacro" />
  <xacro:if value="$(optenv WARTHOG_RIGHT_ARM 0)">
    <joint name="right_arm_joint" type="fixed">
      <origin xyz="0 0 -0.025" rpy="0 0 0" />
      <parent link="right_arm_mount_link"/>
      <child link="right_arm/base_link" />
    </joint>
  </xacro:if>

  <xacro:include filename="$(find mbs_description)/urdf/accessories/arms/left_ur_arm.urdf.xacro" />
  <xacro:if value="$(optenv WARTHOG_LEFT_ARM 0)">
    <joint name="left_arm_joint" type="fixed">
      <origin xyz="0 0 -0.025" rpy="0 0 0" />
      <parent link="left_arm_mount_link"/>
      <child link="left_arm/base_link" />
    </joint>
  </xacro:if>
```

Now center arm will be fine but both  right and left will shrink to the length of center arm i.e. UR3. 

I am not able to sort out this issue, can anyone have an insight on the problem.

Note:

The robot descriptions [UR5e](https://github.com/fmauch/universal_robot/blob/calibration_devel/ur_e_description/urdf/ur5e_robot.urdf.xacro) and [UR3](https://github.com/fmauch/universal_robot/blob/calibration_devel/ur_description/urdf/ur3_robot.urdf.xacro) are the same as on the official [supported repo](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver)

**Note:**
 The same issue is raised on [Universal Robot's repo](https://github.com/ros-industrial/universal_robot/issues/529) repo as currently I don't know where the problem could be.

**Comment by tahir1069** [comment]
![center_broken](https://user-images.githubusercontent.com/13612113/87417403-67966380-c5d0-11ea-9d3d-c2baab70ab44.jpeg)
![front_broken](https://user-images.githubusercontent.com/13612113/87417426-70873500-c5d0-11ea-9d1f-a2c1be1ac3a3.jpeg)

**Comment by dniewinski** [comment]
I believe this issue is how the UR macros are implemented, meaning it's not warthog specific.  The link lengths are defined in xacro:properties, which are likely running into each other.  That explains why either the UR5s or the UR3 break, depending on the order they are loaded.  A workaround for now would be to copy the ur3.urdf.xacro file into your own package and change the property names to be ur3 specific.  Feels dirty, but should work.  It isn't common to mix arm types, so I doubt it is high on a priority list to fix
